name: "Hello world workflow"

on:
  push:
  
jobs:
  print_hello_world_ubuntu:
    name: Hello world Ubuntu!
    runs-on: ubuntu-latest
    
    steps:
      - name: Hello world Ubuntu!
        run: echo 'Hello world'
        
  print_hello_world_windows:
    name: Hello world Windows!
    runs-on: windows-latest
    
    steps:
      - name: Hello world Windows!
        run: echo 'Hello world'
        
  print_hello_world_macos:
    name: Hello world MacOS!
    runs-on: macos-latest      
    
    steps:
      - name: Hello world MacOS!
        run: echo 'Hello world MacOS!'  
  
  print_hello_world_ubuntu_2:
    name: Hello world Ubuntu 2!
    runs-on: ubuntu-latest
    
    steps:
      - name: Hello world Ubuntu 2!
        run: 'date'   
    needs:
      - print_hello_world_ubuntu
      - print_hello_world_windows
      - print_hello_world_macos
    
