name: "Exercicio 1"

on:
  push:
  
jobs:
  print_date_ubuntu:
    name: Print date Ubuntu!
    runs-on: ubuntu-latest
    
    steps:
      - name: Print date Ubuntu!
        run: date
      
  print_date_windows:
    name: Print date Windows!
    runs-on: windows-latest
    
    steps:
      - name: Print date Windows!
        run: date
        
  print_date_macos:
    name: Print date MacOS!
    runs-on: macos-latest      
    
    steps:
      - name: Print date MacOS!
        run: date  
  
  print_date_ubuntu_2:
    name: Print date Ubuntu 2!
    runs-on: ubuntu-latest
    
    needs:
      - print_date_ubuntu
      - print_date_windows
      - print_date_macos
    
    steps:
      - name: Print date Ubuntu 2!
        run: date   
